import type { CatalogManifest } from '../types/artifact.js';
import { ok, type Result } from '../types/result.js';

function pkgImportVar(modulePkg: string): string {
  return 'mod_' + modulePkg.replace(/[^a-zA-Z0-9]/g, '_');
}

/** Deterministic virtual SPA entry (spec §10.2). */
export function renderVirtualEntry(catalog: CatalogManifest): Result<string> {
  const modulePkgs = new Set<string>();
  for (const c of catalog.components) modulePkgs.add(c.module);
  for (const b of catalog.modulesWithBoot) modulePkgs.add(b);

  const sorted = [...modulePkgs].sort();

  const lines: string[] = [
    '// auto-generated by @rntme/blueprint — do not edit',
    "import * as React from 'react';",
    "import { hydrateApp, type ModuleSpec } from '@rntme/ui-runtime/client';",
  ];

  for (const pkg of sorted) {
    const v = pkgImportVar(pkg);
    lines.push(`import * as ${v} from '${pkg}/client';`);
  }

  lines.push('');
  lines.push('const rntmeModuleComponents: Record<string, React.ComponentType<Record<string, unknown>>> = {');

  const entries: string[] = [];
  for (const c of [...catalog.components].sort((a, b) => a.type.localeCompare(b.type))) {
    const v = pkgImportVar(c.module);
    entries.push(`  ${JSON.stringify(c.type)}: ${v}.${c.type},`);
  }
  lines.push(...entries);
  lines.push('};');
  lines.push('');

  lines.push('const rntmeModules: ModuleSpec[] = [');

  if (catalog.modulesWithBoot.length > 0) {
    lines.push(
      ...[...catalog.modulesWithBoot].sort().map((name) => {
        const v = pkgImportVar(name);
        return `  { name: ${JSON.stringify(name)}, boot: ${v}.boot },`;
      }),
    );
  }

  lines.push('];');
  lines.push('');
  lines.push('void hydrateApp({');
  lines.push(`  rootSelector: '#root',`);
  lines.push('  moduleComponents: rntmeModuleComponents,');
  lines.push('  modules: rntmeModules,');
  lines.push('});');
  lines.push('');

  return ok(lines.join('\n'));
}
