FROM oven/bun:1.3.13-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates git \
  && rm -rf /var/lib/apt/lists/*

COPY . .

RUN bun install --frozen-lockfile
RUN bun run -F @rntme/platform-http build
RUN bun run -F @rntme/platform-storage build

CMD ["bun", "run", "test"]
