FROM node:20-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates git \
  && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@9.12.0 --activate

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter '@rntme/platform-http...' build
RUN pnpm --filter '@rntme/platform-storage...' build

CMD ["pnpm", "-r", "run", "test"]
