export const DEPLOY_PROVISION_ERROR_CODES = {
  DEPLOY_PROVISION_MODULE_RESOLVE_FAILED: 'DEPLOY_PROVISION_MODULE_RESOLVE_FAILED',
  DEPLOY_PROVISION_ENTRY_LOAD_FAILED: 'DEPLOY_PROVISION_ENTRY_LOAD_FAILED',
  DEPLOY_PROVISION_TARGET_SECRET_MISSING: 'DEPLOY_PROVISION_TARGET_SECRET_MISSING',
  DEPLOY_PROVISION_TARGET_SECRET_SCHEMA_MISMATCH: 'DEPLOY_PROVISION_TARGET_SECRET_SCHEMA_MISMATCH',
  DEPLOY_PROVISION_TIMEOUT: 'DEPLOY_PROVISION_TIMEOUT',
  DEPLOY_PROVISION_OUTPUT_INVALID: 'DEPLOY_PROVISION_OUTPUT_INVALID',
  DEPLOY_PROVISION_VENDOR_FAILED: 'DEPLOY_PROVISION_VENDOR_FAILED',
} as const;

export type DeploymentProvisionErrorCode = keyof typeof DEPLOY_PROVISION_ERROR_CODES;

export type DeploymentProvisionError = Readonly<{
  code: DeploymentProvisionErrorCode | string;
  message: string;
  module?: string;
}>;
