export const DEPLOY_CORE_ERROR_CODES = {
  DEPLOY_PLAN_UNSUPPORTED_PRODUCTION_MODE: 'DEPLOY_PLAN_UNSUPPORTED_PRODUCTION_MODE',
  DEPLOY_PLAN_INVALID_ENVIRONMENT: 'DEPLOY_PLAN_INVALID_ENVIRONMENT',
  DEPLOY_PLAN_MISSING_ORG_SLUG: 'DEPLOY_PLAN_MISSING_ORG_SLUG',
  DEPLOY_PLAN_MISSING_EVENT_BUS: 'DEPLOY_PLAN_MISSING_EVENT_BUS',
  DEPLOY_PLAN_EVENT_BUS_MODE_UNSUPPORTED: 'DEPLOY_PLAN_EVENT_BUS_MODE_UNSUPPORTED',
  DEPLOY_PLAN_EVENT_BUS_PROVIDER_UNSUPPORTED: 'DEPLOY_PLAN_EVENT_BUS_PROVIDER_UNSUPPORTED',
  DEPLOY_PLAN_EVENT_BUS_IMAGE_INVALID: 'DEPLOY_PLAN_EVENT_BUS_IMAGE_INVALID',
  DEPLOY_PLAN_EVENT_BUS_SASL_INCOMPLETE: 'DEPLOY_PLAN_EVENT_BUS_SASL_INCOMPLETE',
  DEPLOY_PLAN_EVENT_BUS_SASL_MECHANISM_UNSUPPORTED:
    'DEPLOY_PLAN_EVENT_BUS_SASL_MECHANISM_UNSUPPORTED',
  DEPLOY_PLAN_MISSING_MODULE_IMAGE: 'DEPLOY_PLAN_MISSING_MODULE_IMAGE',
  DEPLOY_PLAN_PUBLIC_MODULE_NOT_EXPOSED: 'DEPLOY_PLAN_PUBLIC_MODULE_NOT_EXPOSED',
  DEPLOY_PLAN_UNSUPPORTED_MIDDLEWARE: 'DEPLOY_PLAN_UNSUPPORTED_MIDDLEWARE',
  DEPLOY_PLAN_AUTH_MIDDLEWARE_INCOMPLETE: 'DEPLOY_PLAN_AUTH_MIDDLEWARE_INCOMPLETE',
  DEPLOY_PLAN_AUTH_MODULE_WORKLOAD_MISSING: 'DEPLOY_PLAN_AUTH_MODULE_WORKLOAD_MISSING',
  DEPLOY_PLAN_AUTH_MODULE_ENV_INCOMPLETE: 'DEPLOY_PLAN_AUTH_MODULE_ENV_INCOMPLETE',
  DEPLOY_PLAN_AUTH_CLIENT_ID_MISSING: 'DEPLOY_PLAN_AUTH_CLIENT_ID_MISSING',
  DEPLOY_PLAN_MISSING_POLICY_VALUE: 'DEPLOY_PLAN_MISSING_POLICY_VALUE',
  DEPLOY_PLAN_MISSING_POLICY_VALUE_HINT: 'DEPLOY_PLAN_MISSING_POLICY_VALUE_HINT',
  DEPLOY_PLAN_ROUTE_TARGET_MISSING_WORKLOAD: 'DEPLOY_PLAN_ROUTE_TARGET_MISSING_WORKLOAD',
  DEPLOY_PLAN_MISSING_MIDDLEWARE_DECLARATION: 'DEPLOY_PLAN_MISSING_MIDDLEWARE_DECLARATION',
  DEPLOY_PLAN_MOUNT_TARGET_MISSING_ROUTE: 'DEPLOY_PLAN_MOUNT_TARGET_MISSING_ROUTE',
  DEPLOY_PLAN_AUTH_MODULE_HTTP_INTROSPECT_MISSING: 'DEPLOY_PLAN_AUTH_MODULE_HTTP_INTROSPECT_MISSING',
  DEPLOY_PLAN_TARGET_VAR_MISSING: 'DEPLOY_PLAN_TARGET_VAR_MISSING',
  DEPLOY_PLAN_VAR_FROM_PATH_INVALID: 'DEPLOY_PLAN_VAR_FROM_PATH_INVALID',
  BLUEPRINT_VAR_PROVISION_PATH_INVALID: 'BLUEPRINT_VAR_PROVISION_PATH_INVALID',
  BLUEPRINT_VAR_PROVISION_MODULE_MISSING: 'BLUEPRINT_VAR_PROVISION_MODULE_MISSING',
  BLUEPRINT_VAR_PROVISION_OUTPUT_NOT_DECLARED: 'BLUEPRINT_VAR_PROVISION_OUTPUT_NOT_DECLARED',
  BLUEPRINT_VAR_PROVISION_OUTPUT_MISSING: 'BLUEPRINT_VAR_PROVISION_OUTPUT_MISSING',
  BLUEPRINT_VAR_PROVISION_PATH_NOT_FOUND: 'BLUEPRINT_VAR_PROVISION_PATH_NOT_FOUND',
  DEPLOY_PLAN_WORKFLOWS_REQUIRE_EVENT_BUS: 'DEPLOY_PLAN_WORKFLOWS_REQUIRE_EVENT_BUS',
  DEPLOY_PLAN_WORKFLOWS_REQUIRE_OPERATON: 'DEPLOY_PLAN_WORKFLOWS_REQUIRE_OPERATON',
  DEPLOY_PLAN_WORKFLOWS_REQUIRE_OPERATON_HINT: 'DEPLOY_PLAN_WORKFLOWS_REQUIRE_OPERATON_HINT',
  DEPLOY_PLAN_WORKFLOWS_WORKER_IMAGE_MISSING: 'DEPLOY_PLAN_WORKFLOWS_WORKER_IMAGE_MISSING',
  DEPLOY_PLAN_WORKFLOWS_BINDING_GRPC_UNAVAILABLE: 'DEPLOY_PLAN_WORKFLOWS_BINDING_GRPC_UNAVAILABLE',
  DEPLOY_PLAN_WORKFLOWS_BINDING_GRPC_PROTO_UNAVAILABLE:
    'DEPLOY_PLAN_WORKFLOWS_BINDING_GRPC_PROTO_UNAVAILABLE',
  DEPLOY_PLAN_WORKFLOWS_UNSUPPORTED_ENGINE: 'DEPLOY_PLAN_WORKFLOWS_UNSUPPORTED_ENGINE',
  DEPLOY_PLAN_WORKFLOW_FILE_MISSING: 'DEPLOY_PLAN_WORKFLOW_FILE_MISSING',
  DEPLOY_PLAN_REDPANDA_CONSOLE_EVENT_BUS_INVALID: 'DEPLOY_PLAN_REDPANDA_CONSOLE_EVENT_BUS_INVALID',
  DEPLOY_PLAN_REDPANDA_CONSOLE_USERNAME_REQUIRED: 'DEPLOY_PLAN_REDPANDA_CONSOLE_USERNAME_REQUIRED',
  DEPLOY_PLAN_REDPANDA_CONSOLE_HTPASSWD_REF_REQUIRED: 'DEPLOY_PLAN_REDPANDA_CONSOLE_HTPASSWD_REF_REQUIRED',
  DEPLOY_PLAN_REDPANDA_CONSOLE_IMAGE_INVALID: 'DEPLOY_PLAN_REDPANDA_CONSOLE_IMAGE_INVALID',
  DEPLOY_PLAN_REDPANDA_CONSOLE_PUBLIC_URL_INVALID: 'DEPLOY_PLAN_REDPANDA_CONSOLE_PUBLIC_URL_INVALID',
  DEPLOY_PLAN_REDPANDA_CONSOLE_PUBLIC_URL_REQUIRED: 'DEPLOY_PLAN_REDPANDA_CONSOLE_PUBLIC_URL_REQUIRED',
} as const;

export type DeploymentPlanErrorCode = keyof typeof DEPLOY_CORE_ERROR_CODES;

export type DeploymentPlanError = {
  readonly code: DeploymentPlanErrorCode;
  readonly message: string;
  readonly path?: string;
  readonly service?: string;
  readonly route?: string;
  readonly middleware?: string;
  readonly moduleSlug?: string;
  readonly policy?: string;
  readonly varName?: string;
  readonly fromPath?: string;
  readonly targetSlug?: string;
  readonly cause?: readonly DeploymentPlanErrorNode[];
};

export type DeploymentPlanErrorNode = {
  readonly code: string;
  readonly message: string;
  readonly path?: string;
  readonly cause?: readonly DeploymentPlanErrorNode[];
};
