import { describe, expect, it } from 'bun:test';
import {
  GRPC_STATUS_ALREADY_EXISTS,
  GRPC_STATUS_INVALID_ARGUMENT,
  GRPC_STATUS_NOT_FOUND,
  GRPC_STATUS_PERMISSION_DENIED,
  GRPC_STATUS_RESOURCE_EXHAUSTED,
  GRPC_STATUS_UNAUTHENTICATED,
  GRPC_STATUS_UNAVAILABLE,
  mapWorkOSError,
} from '../src/errors.js';

describe('WorkOS error mapping', () => {
  it.each([
    [400, GRPC_STATUS_INVALID_ARGUMENT, 'IDENTITY_VENDOR_INVALID_REQUEST'],
    [422, GRPC_STATUS_INVALID_ARGUMENT, 'IDENTITY_VENDOR_INVALID_REQUEST'],
    [401, GRPC_STATUS_UNAUTHENTICATED, 'IDENTITY_VENDOR_UNAUTHORIZED'],
    [403, GRPC_STATUS_PERMISSION_DENIED, 'IDENTITY_VENDOR_UNAUTHORIZED'],
    [404, GRPC_STATUS_NOT_FOUND, 'IDENTITY_REFERENCES_USER_NOT_FOUND'],
    [409, GRPC_STATUS_ALREADY_EXISTS, 'IDENTITY_CONSISTENCY_DUPLICATE_EMAIL'],
    [429, GRPC_STATUS_RESOURCE_EXHAUSTED, 'IDENTITY_VENDOR_RATE_LIMITED'],
    [500, GRPC_STATUS_UNAVAILABLE, 'IDENTITY_VENDOR_UNAVAILABLE'],
    [503, GRPC_STATUS_UNAVAILABLE, 'IDENTITY_VENDOR_UNAVAILABLE'],
  ])('maps WorkOS HTTP %i to gRPC code %i and canonical code %s', (status, code, canonicalCode) => {
    const mapped = mapWorkOSError({ status, message: `WorkOS ${status}` }, 'IDENTITY_REFERENCES_USER_NOT_FOUND');

    expect(mapped).toMatchObject({
      code,
      canonicalCode,
      message: `WorkOS ${status}`,
    });
  });
});
