export const AMOCRM_SUPPORTED_RPCS = [
  'GetContact',
  'ListContacts',
  'CreateContact',
  'UpdateContact',
  'DeleteContact',
  'GetCompany',
  'ListCompanies',
  'CreateCompany',
  'UpdateCompany',
  'DeleteCompany',
  'GetDeal',
  'ListDeals',
  'CreateDeal',
  'UpdateDeal',
  'DeleteDeal',
  'GetActivity',
  'ListActivities',
  'CreateActivity',
  'GetNote',
  'ListNotes',
  'CreateNote',
  'ListPipelines',
  'ListCustomFieldDefinitions',
  'CreateAssociation',
  'DeleteAssociation',
] as const;

export const AMOCRM_UNSUPPORTED_RPCS = [] as const;

export const AMOCRM_SUPPORTED_EVENTS = [
  'rntme.crm.v1.ContactCreated',
  'rntme.crm.v1.ContactUpdated',
  'rntme.crm.v1.ContactDeleted',
  'rntme.crm.v1.CompanyCreated',
  'rntme.crm.v1.CompanyUpdated',
  'rntme.crm.v1.CompanyDeleted',
  'rntme.crm.v1.DealCreated',
  'rntme.crm.v1.DealUpdated',
  'rntme.crm.v1.DealStageChanged',
  'rntme.crm.v1.DealClosed',
  'rntme.crm.v1.ActivityCreated',
  'rntme.crm.v1.ActivityUpdated',
  'rntme.crm.v1.ActivityDeleted',
  'rntme.crm.v1.NoteCreated',
  'rntme.crm.v1.NoteDeleted',
  'rntme.crm.v1.AssociationCreated',
  'rntme.crm.v1.AssociationDeleted',
  'rntme.crm.v1.AsyncJobSubmitted',
  'rntme.crm.v1.AsyncJobStatusChanged',
  'rntme.crm.v1.AsyncJobCompleted',
  'rntme.crm.v1.AsyncJobFailed',
] as const;

export type SupportedAmoCrmRpc = (typeof AMOCRM_SUPPORTED_RPCS)[number];
